#!/bin/bash
read -p 'What repo would you like to use? ' repovar
read -p 'What would you like your DockerHub image to be called? ' imagevar
read -p 'What is your DockerHub username? ' hubvar

git clone $repovar

cd $repovar

docker build . -t $hubvar/$imagevar

docker push $hubvar/$imagevar
