version: '3.8'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
    container_name: frontendcontainer
  
  backend:
    image: backend_redis
    ports:
      - 8080:8080
    container_name: backendcontainer

  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: rediscontainer
